### ISSUE TITLE
Intermittent disappearance

### ISSUE THREAD

**Issue by FlooferDoofer** [ArchitectSMP/k8s-gitops#120]
Player SH4D0WK1LL3R does not always appear in the tab list and is not visible in the game for players after logging in.
For admin he sometimes does and sometimes doesn't appear in the tablist as [member] -name- while invisible to others.
He is also not visible to himself in F5 and in his own tab list.
Shadow can chat normally with other players despite this happening.
So far this has happened 3 times, each time in the creative server.

Player uses Vanilla launcher with Fabric mods.
No other players have had this happen to them as far as we know.

![shadowmember](https://user-images.githubusercontent.com/79203949/111053004-818a8d80-8460-11eb-816e-38edad39f8ac.png)

**Comment by pengolod** [comment]
It's because he's a ghost, obviously :p

**Comment by bloodycoffin** [comment]
Asked player to try the following. This is client-side which influences the server - not a server problem.

After you've loaded the world, then go to the "Help & Options" menu, then "Settings", then "Reset to Defaults" which will clear all the settings changes regardless of whether they were due to the bug or ones you've set manually. You can then go to the different settings options and re-change various ones to your preferences.
