### ISSUE TITLE
Setup Development environment for Architect SMP

### ISSUE THREAD

**Issue by bloodycoffin** [ArchitectSMP/k8s-gitops#23]
To prevent testing in production since we are now stable it would be beneficial to setup a Development environment to test any future enhancements or additions.

**Comment by ChipWolf** [comment]
So this is where things can get interesting; there's many ways to approach this.

Let's start by thinking about the requirements:
- Ability to test changes before promoting them to prod in order to reduce change impact on users.
- Mechanism to safely test changes without accidentally, directly or indirectly, affecting prod.
- Agility to quickly test changes without faffing around.

- The most complete solution would be to keep a second `dev` cluster which is practically identical to prod.
In this new cluster; Flux would watch the `dev` branch, while the prod cluster would continue to watch the `main` branch.
  - Advantage: it's less likely to run into quirks of the production environment when promoting known-good changes from dev.
  - Disadvantage: overhead; the cluster would essentially be running twice _(albeit, on a significantly smaller cloud instance which can easily be destroyed and redeployed when required)_.

- The lightest solution would be to just temporarily copy deployments when testing.
  - Advantage: little to no overhead.
  - Disadvantage: some fundamental deployments cannot be tested this way _(i.e. the load balancer)_. Also, this would rely on a second pull request per change; one to push the test deployment, the other to remove it _(and modify the prod deployment if the test was successful)_.

- A middle ground solution would be to generate a `dev` namespace. This new namespace would duplicate the existing `default` namespace. The `default` namespace contains the Minecraft servers, database, and proxy which are most likely to be subject to change which could impact users.
  - Advantage: reduced overhead relative to the first solution. The test deployments can be modified from the `dev` branch without promoting to `main` and it doesn't require additional servers for testing.
  - Disadvantage: some fundamental deployments cannot be tested this way, such as the load balancer.

I'm leaning toward the middle ground solution as a nice balance between overhead and function. Despite the disadvantage with that solution; deployments which cannot be tested easily are either the least likely deployments to require changes _(i.e. metallb or flux), or deployments which don't impact users _(i.e. monitoring)_.

**Comment by bloodycoffin** [comment]
The middle-ground solution seems to suit us the best.
What is the effort to set this up? 
It would simply be turned on by scaling the deployment to 1, with other words the way I would start up the creative and survival environment after scaling it down for restart? Any config changes required? How do we push things to production, a copy-paste scenario?
