### ISSUE TITLE
Replace Aphelia with DiscordSRV

### ISSUE THREAD

**Issue by ChipWolf** [ArchitectSMP/k8s-gitops#92]
We're going full circle here, Aphelia has barely any config options and we can't silence join/leaves without modifying code and building our own version of the plugin. It also depends on a Discord bot we don't operate and could cease functioning at any point, so based on those things we should replace it with DiscordSRV.

We used DiscordSRV previously before Aphelia but had to replace it with Aphelia as `gChat` our previous global chat solution cancels message events to the local servers. As DiscordSRV is installed only on the local servers, not the proxy, it couldn't be used with `gChat`.
Now we're using MultiChat & it has support for DiscordSRV, so we can go back to using it which will also partially resolve #76

**Comment by bloodycoffin** [comment]
@ChipWolf is Aphelia in any way implemented as plugin in the pods or only in Discord? I don't immediately see it on Dev to try and implement this myself so I wanted to double check there are no configs I miss.

**Comment by ChipWolf** [comment]
> 
> 
> @ChipWolf is Aphelia in any way implemented as plugin in the pods or only in Discord? I don't immediately see it on Dev to try and implement this myself so I wanted to double check there are no configs I miss.

It's on the proxy, it's called Hermes for [whatever reason](https://aphelia.github.io/hermes/)

**Comment by bloodycoffin** [comment]
Tested in DEV, seemed okay
Put into PROD, placeholder xAntiAFK acting odd since reload papi
![image_2021-03-05_214619](https://user-images.githubusercontent.com/78444107/110171582-3804c780-7dfc-11eb-8734-beabc7684d27.png)

**Comment by bloodycoffin** [comment]
This is setup now without problems :-)

**Comment by ChipWolf** [comment]
Probably worth @AwesomestCode having visibility of this. Our biggest issue with Aphelia is the lack of config to silence join/leaves, especially for vanished members. It's a far simpler/better solution other than that.

**Comment by raymondjxu** [comment]
As of 21 November 2020, Aphelia is no longer actively maintained except for security bug fixes, mainly due to the trouble getting it off the ground (not many users were interested) and my disliking of Discord's new Bot Verification policy.
I've since moved on to other projects though, some also targeting Minecraft server owners.
It's very simple to disable login/leave messages if you're willing to recompile the plugin, though: just disable sending the JOIN message.
I have released an entirely self-hosted version of you need it if/when I stop hosting it (I usually guarantee longevity of my software long after deprecation, it's already been several months though).
